import sys
import os
import json
import torch

# Add utils directory to path
module_dir = "../utils"
sys.path.append(os.path.abspath(module_dir))

try:
    from llm_utils import *
except ImportError:
    print(f"Error: Could not import 'utils'. Make sure llm_utils.py is in '{module_dir}'")
    sys.exit(1)

# Configuration
# ==============================================================================
# BEST_CONFIG_PATH = "Optuna-unsloth-SmolLM2-unsloth-bnb-4bit-multiclass_some_modules_best_config.json"
BEST_CONFIG_PATH = "best_config.json" # Rename your JSON or point to the specific file generated by Optuna
FINAL_MODEL_OUTPUT_DIR = "./final_model_lora"
MODEL_NAME = "unsloth/SmolLM2-1.7B-Instruct-bnb-4bit"

TEST_DATASET_PATH = "./testDataset.csv"
TRAIN_DATASET_PATH = "./trainDataset.csv"

# Prompt Templates (Must match search configuration)
# ==============================================================================
user_prompt = """
You are an AI system tasked with evaluating the textual coherence of a short story based on its title and content. Your job is to perform a sentence-by-sentence analysis of the story and identify any coherence issues. Each problematic sentence must be tagged with the appropriate reason code, explained below.

## Instruction:
Analyze the given story sentence by sentence. Identify any coherence issues and assign the relevant tags from the list below. Each problematic sentence should include a short explanation and be marked with one or more of the following reason tags:

### Reason Tags:
- <r1>1</r1> - the sentence doesn't make sense
- <r2>1</r2> - the sentence discusses an entity which has not been introduced yet
- <r3>1</r3> - the relation between this sentence and previous ones doesn't make sense
- <r4>1</r4> - the sentence contains information inconsistent with previous presented data
- <r5>1</r5> - the sentence contains information inconsistent with the knowledge about the world
- <r6>1</r6> - the sentence is not relevant to the title
- <r7>1</r7> - the sentence is not relevant to previous data in the story

IMPORTANT: You MUST follow the EXACT format shown below. Analyze each sentence individually and assign appropriate reason tags (<r1> through <r7>) to each problematic sentence. Use the tags exactly as shown.

Finally, you will provide the score of the text coherence using the following format.
## Scoring criteria:
- <score>1</score> if the story is not coherent at all.
- <score>2</score> if the story is not coherent.
- <score>3</score> if the story is maybe yes, maybe not coherent.
- <score>4</score> if the story is coherent.
- <score>5</score> if the story is definitely coherent.

## Response Format:
1. Overall Coherence:
   - [Brief assessment of whether the story is coherent or not]
   
2. Problematic sentences:
   - "[Exact problematic sentence]" !Important: don not repeat the sentences, each sentence must be unique!
     - Reason: [Brief explanation]
     - Tags: <rX>1</rX>
     
3. Conclusion:
   - [Summary conclusion about the story’s coherence]
   
4. Score:
   - <score>[1,2,3,4 or 5]</score>

## Input:
{}
"""

assistant_prompt = """
## Response:
{}
4. Score:
{}"""

def load_best_params(path):
    if not os.path.exists(path):
        print(f"Error: Configuration file '{path}' not found.")
        sys.exit(1)
        
    with open(path, 'r') as f:
        params = json.load(f)
    
    print(f"Loaded best parameters from {path}:")
    print(json.dumps(params, indent=4))
    
    # Handle key mismatch between Optuna search space and train function arguments
    # Optuna stored 'target_module', but train_lora_model expects 'train_target_modules'
    if "target_module" in params:
        params["train_target_modules"] = params.pop("target_module")
        
    return params

def main():
    # 1. Load Parameters
    best_params = load_best_params(BEST_CONFIG_PATH)

    # 2. Initialize Model
    print("\n>>> Initializing Model...")
    llm = LLMModel(model_name=MODEL_NAME)
    llm.load_pretrained_model(max_seq_length=1024 * 5)

    # 3. Prepare Datasets
    print("\n>>> Preparing Datasets...")
    llm.load_train_csv_dataset(TRAIN_DATASET_PATH)
    llm.load_test_csv_dataset(TEST_DATASET_PATH)
    
    # Create dataset (Use the same split ratio as your search, or use full data if desired)
    llm.create_dataset(
        user_prompt, 
        assistant_prompt, 
        test_size=0.1, 
        balance=False
    )

    # 4. Train Model
    print("\n>>> Starting Final Training...")
    
    # We unpack the best_params dictionary into the function arguments
    # We explicitly set optuna_search=False to prevent trial reporting logic
    training_result = llm.train_lora_model(
        trial=None,
        optuna_search=False,
        clean_start=False, # We already loaded the model above
        wandb_project_name="Final-Production-Training",
        report_to="wandb",
        **best_params
    )
    
    if training_result == -np.inf:
        print("Training Failed.")
        sys.exit(1)

    # 5. Save Model
    print(f"\n>>> Saving LoRA adapters to {FINAL_MODEL_OUTPUT_DIR}...")
    llm.save_lora_model(MODEL_NAME, FINAL_MODEL_OUTPUT_DIR)

    # 6. Evaluation
    print("\n>>> Starting Final Evaluation...")
    
    # Define prompt for evaluation (matches format used in generation)
    eval_prompt = user_prompt + "\n## Response:"
    
    y_true, y_pred = llm.evaluate_lora_mode(
        prompt=eval_prompt,
        batch_size=8, # Adjust based on your GPU VRAM
        max_new_tokens=1024,
        temperature=0.1,
        stop_on_first_input=False
    )

    # 7. Show Metrics
    print("\n>>> Final Metrics:")
    llm.show_metrics(y_true, y_pred)
    
    print("\n>>> Process Complete.")

if __name__ == "__main__":
    main()